{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Jupyter CadQuery\n",
    "\n",
    "Welcome to Jupyter CadQuery! This notebook provides an interactive environment for creating 3D CAD models using Python. [Jupyter CadQuery](https://github.com/bernhard-42/jupyter-cadquery) combines the power of [CadQuery](https://cadquery.readthedocs.io/en/latest/) with Jupyter's interactive interface, making it easy to design and visualize 3D models.\n",
    "\n",
    "## What is CadQuery?\n",
    "\n",
    "CadQuery is a Python library for creating parametric 3D CAD models. It's inspired by OpenSCAD but uses Python as its programming language, giving you access to all the power and flexibility of Python for your CAD designs.\n",
    "\n",
    "## Features\n",
    "\n",
    "- Create parametric 3D models using Python\n",
    "- Interactive visualization in Jupyter notebooks\n",
    "- Export models to various formats (STL, STEP, etc.)\n",
    "- Full Python programming capabilities\n",
    "- Parametric design with variables and functions\n",
    "\n",
    "## Getting Started\n",
    "\n",
    "This notebook is pre-configured with [CadQuery](https://cadquery.readthedocs.io/en/latest/) and [Jupyter CadQuery](https://github.com/bernhard-42/jupyter-cadquery). The example below is copied from the CadQuery examples and demonstrates how to create a parametric box with customizable dimensions. You can modify the parameters to create different variations of the box.\n",
    "\n",
    "For more information, visit the [CadQuery documentation](https://cadquery.readthedocs.io/en/latest/) and if you're unsure of how to use Jupyter Lab (this website), there's a quickstart tutorial [here](https://justinbois.github.io/bootcamp/2020_fsri/lessons/l01_welcome.html#Launching-a-Jupyter-notebook)."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Let's get to it!\n",
    "\n",
    "First we need to import the necessary libraries. \n",
    "\n",
    "We also configure the viewer in the side panel."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import cadquery as cq\n",
    "import jupyter_cadquery as jcq\n",
    "\n",
    "jcq.set_defaults(axes=True, timeit=False)\n",
    "jcq.open_viewer(\"Jupyter CadQuery - Example\", cad_width=640, height=480, glass=True)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Now we are ready to create our box. Run the following cell and then tweak the parameters \n",
    "and re-run to see how you can change the results."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# parameter definitions\n",
    "p_outerWidth = 100.0  # Outer width of box enclosure\n",
    "p_outerLength = 150.0  # Outer length of box enclosure\n",
    "p_outerHeight = 50.0  # Outer height of box enclosure\n",
    "\n",
    "p_thickness = 3.0  # Thickness of the box walls\n",
    "p_sideRadius = 10.0  # Radius for the curves around the sides of the box\n",
    "p_topAndBottomRadius = (\n",
    "    2.0  # Radius for the curves on the top and bottom edges of the box\n",
    ")\n",
    "\n",
    "p_screwpostInset = 12.0  # How far in from the edges the screw posts should be place.\n",
    "p_screwpostID = 4.0  # Inner Diameter of the screw post holes, should be roughly screw diameter not including threads\n",
    "p_screwpostOD = 10.0  # Outer Diameter of the screw posts.\\nDetermines overall thickness of the posts\n",
    "\n",
    "p_boreDiameter = 8.0  # Diameter of the counterbore hole, if any\n",
    "p_boreDepth = 1.0  # Depth of the counterbore hole, if\n",
    "p_countersinkDiameter = 0.0  # Outer diameter of countersink. Should roughly match the outer diameter of the screw head\n",
    "p_countersinkAngle = 90.0  # Countersink angle (complete angle between opposite sides, not from center to one side)\n",
    "p_lipHeight = 1.0  # Height of lip on the underside of the lid.\\nSits inside the box body for a snug fit.\n",
    "\n",
    "# outer shell\n",
    "oshell = (\n",
    "    cq.Workplane(\"XY\")\n",
    "    .rect(p_outerWidth, p_outerLength)\n",
    "    .extrude(p_outerHeight + p_lipHeight)\n",
    ")\n",
    "\n",
    "# weird geometry happens if we make the fillets in the wrong order\n",
    "if p_sideRadius > p_topAndBottomRadius:\n",
    "    oshell = oshell.edges(\"|Z\").fillet(p_sideRadius)\n",
    "    oshell = oshell.edges(\"#Z\").fillet(p_topAndBottomRadius)\n",
    "else:\n",
    "    oshell = oshell.edges(\"#Z\").fillet(p_topAndBottomRadius)\n",
    "    oshell = oshell.edges(\"|Z\").fillet(p_sideRadius)\n",
    "\n",
    "# inner shell\n",
    "ishell = (\n",
    "    oshell.faces(\"<Z\")\n",
    "    .workplane(p_thickness, True)\n",
    "    .rect((p_outerWidth - 2.0 * p_thickness), (p_outerLength - 2.0 * p_thickness))\n",
    "    .extrude(\n",
    "        (p_outerHeight - 2.0 * p_thickness), False\n",
    "    )  # set combine false to produce just the new boss\n",
    ")\n",
    "ishell = ishell.edges(\"|Z\").fillet(p_sideRadius - p_thickness)\n",
    "\n",
    "# make the box outer box\n",
    "box = oshell.cut(ishell)\n",
    "\n",
    "# make the screw posts\n",
    "POSTWIDTH = p_outerWidth - 2.0 * p_screwpostInset\n",
    "POSTLENGTH = p_outerLength - 2.0 * p_screwpostInset\n",
    "\n",
    "box = (\n",
    "    box.faces(\">Z\")\n",
    "    .workplane(-p_thickness)\n",
    "    .rect(POSTWIDTH, POSTLENGTH, forConstruction=True)\n",
    "    .vertices()\n",
    "    .circle(p_screwpostOD / 2.0)\n",
    "    .circle(p_screwpostID / 2.0)\n",
    "    .extrude(-1.0 * (p_outerHeight + p_lipHeight - p_thickness), True)\n",
    ")\n",
    "\n",
    "# split lid into top and bottom parts\n",
    "(lid, bottom) = (\n",
    "    box.faces(\">Z\")\n",
    "    .workplane(-p_thickness - p_lipHeight)\n",
    "    .split(keepTop=True, keepBottom=True)\n",
    "    .all()\n",
    ")  # splits into two solids\n",
    "\n",
    "# translate the lid, and subtract the bottom from it to produce the lid inset\n",
    "lowerLid = lid.translate((0, 0, -p_lipHeight))\n",
    "cutlip = lowerLid.cut(bottom)\n",
    "\n",
    "# compute centers for screw holes\n",
    "topOfLidCenters = (\n",
    "    cutlip.faces(\">Z\")\n",
    "    .workplane(centerOption=\"CenterOfMass\")\n",
    "    .rect(POSTWIDTH, POSTLENGTH, forConstruction=True)\n",
    "    .vertices()\n",
    ")\n",
    "\n",
    "# add holes of the desired type\n",
    "if p_boreDiameter > 0 and p_boreDepth > 0:\n",
    "    topOfLid = topOfLidCenters.cboreHole(\n",
    "        p_screwpostID, p_boreDiameter, p_boreDepth, 2.0 * p_thickness\n",
    "    )\n",
    "elif p_countersinkDiameter > 0 and p_countersinkAngle > 0:\n",
    "    topOfLid = topOfLidCenters.cskHole(\n",
    "        p_screwpostID, p_countersinkDiameter, p_countersinkAngle, 2.0 * p_thickness\n",
    "    )\n",
    "else:\n",
    "    topOfLid = topOfLidCenters.hole(p_screwpostID, 2.0 * p_thickness)\n",
    "\n",
    "\n",
    "\n",
    "assy = cq.Assembly(None, name=\"parametric box\")\n",
    "assy.add(bottom, name=\"bottom\")\n",
    "assy.add(topOfLid, name=\"lid\", loc=cq.Location((0, 0, 30)))\n",
    "assy"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Finally, you can export the models to STL files that you can then import into your 3D printer software to slice and print."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "cq.exporters.export(bottom, \"box-bottom.stl\")\n",
    "cq.exporters.export(topOfLid, \"box-lid.stl\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.16"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
